name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.9+9'

      - name: Decode jks
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'store.jks'
          fileDir: './'
          encodedString: ${{ secrets.STORE_FILE_BASE64 }}

      - name: Generate local.properties
        run: |
          touch ./local.properties
          echo "STORE_FILE=$(realpath -s ./store.jks)" >> ./local.properties
          echo 'STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}' >> ./local.properties
          echo 'KEY_ALIAS=${{ secrets.KEY_ALIAS }}' >> ./local.properties
          echo 'KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}' >> ./local.properties

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./app/build/outputs/apk/release/*.apk
